version: "3.9"

services:
  trading-bot:
    build: .
    container_name: trading_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BASE_URL=${BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./chat_history:/app/chat_history
      - ./users:/app/users
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
